AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  AddReservation:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          CINEMA_TABLE: !Ref CinemaTable
      FunctionName: AddReservation
      Handler: app.add_reservation
      Runtime: python3.9
      CodeUri: build
      Policies:
        - DynamoDBWritePolicy:
            TableName:
              !Ref CinemaTable
      Events:
        PostUser:
          Type: Api
          Properties:
            RestApiId: !Ref CinemaAPI
            Path: "/addReservation"
            Method: POST

  DisplayShow:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          CINEMA_TABLE: !Ref CinemaTable
      FunctionName: DisplayShow
      Handler: app.display_show
      Runtime: python3.9
      CodeUri: build
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              !Ref CinemaTable
      Events:
        PostUser:
          Type: Api
          Properties:
            RestApiId: !Ref CinemaAPI
            Path: "/display_show/show/{show_id}"
            Method: GET

  DisplayMovie:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          CINEMA_TABLE: !Ref CinemaTable
      FunctionName: DisplayMovie
      Handler: app.display_movie
      Runtime: python3.9
      CodeUri: build
      Policies:
        - DynamoDBReadPolicy:
            TableName:
              !Ref CinemaTable
      Events:
        PostUser:
          Type: Api
          Properties:
            RestApiId: !Ref CinemaAPI
            Path: "/display_movie"
            Method: GET

  CinemaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cinema-table
      AttributeDefinitions:
        - 
          AttributeName: "pk"
          AttributeType: "S"
        - 
          AttributeName: "sk"
          AttributeType: "S"
      KeySchema: 
        - 
          AttributeName: "pk"
          KeyType: "HASH"
        - 
          AttributeName: "sk"
          KeyType: "RANGE"
      ProvisionedThroughput: 
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  CinemaAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Name: cinema-api
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: swaggerSpec.yaml
      