AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    Environment:
        Type: String
        Default: "dev"

Resources:
    MyBucket:
        Type: AWS::S3::Bucket
        Properties:
            BucketName: !Join 
            - ''
            - - 'bucket-mojix-12-'
              - !Ref Environment
            AccessControl: PublicRead
            WebsiteConfiguration:
                IndexDocument: index.html
                ErrorDocument: error.html
            Tags:
                - Key: Company
                  Value: CodeRoad
    
    MyBucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
            Bucket: !Ref MyBucket
            PolicyDocument:
                Id: MyPolicy
                Version: 2012-10-17
                Statement:
                  - Sid: PublicReadForGetBucketObjects
                    Effect: Allow
                    Principal: '*'
                    Action: 's3:GetObject'
                    Resource: !Join 
                      - ''
                      - - 'arn:aws:s3:::'
                        - !Ref MyBucket
                        - /*
                    
Outputs:
    WebsiteUrl:
        Value: !GetAtt MyBucket.WebsiteURL
        Description: The website url
